version: '3'
services:
  app:
    image: joselfonsecadt/nginx-php7.3:latest
    volumes:
      - ./:/var/www/html
    links:
      - mysql
      - redis
    ports:
      - 8080:80
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: castelan
      MYSQL_DATABASE: laravel-docker
    volumes:
      - ./docker/mysql/data/:/var/lib/mysql
    ports:
      - 33060:3306
  redis:
    image: redis:5-alpine
    ports:
      - 6379:6379